"""All site copy, English and Spanish. Edit text here, then run:  python tools/build.py
Inline links in text use [label](target) where target is a page key like retaining-walls or contact.
Spanish text is machine-assisted and should be reviewed by a native speaker before relying on it.
"""

SITE = dict(
    url="https://sysopx786.github.io/wolfs-landscaping-WEBSITE",
    name="Wolf's Landscaping Services",
    phone_display="610-357-1098",
    phone_tel="+16103571098",
    google_write_review_url="https://search.google.com/local/writereview?placeid=ChIJ0VPVILEDmSgRVGItL-XDgCI",  # opens the review box (Google asks visitors to sign in first)
    street="429 Main St", city="Royersford", state="PA", zip="19468",
    maps_url="https://www.google.com/maps?cid=2486202383414944340",
    directions_url="https://www.google.com/maps/dir/?api=1&destination=429+Main+St,+Royersford,+PA+19468",
    google_reviews_url="https://www.google.com/maps?cid=2486202383414944340",  # Google Business Profile: Wolf's Landscaping Services
    areas=["Royersford, PA", "Chester County, PA"],
)

# Unverified list: owner should confirm or edit
TOWNS = ["Royersford", "Spring City", "Oaks", "Collegeville", "Kimberton",
         "Chester Springs", "Malvern", "Exton", "Downingtown", "West Chester", "Valley Forge"]

# Owner details for the About page. Leave empty until the owner confirms them: anything empty is simply not shown.
# Fill in, then run: python tools/build.py
OWNER = dict(
    name="Bryan J. Wolf",
    role={"en": "Owner", "es": "Propietario"},
    story={"en": [], "es": []},        # paragraphs about how the business started
    credentials={"en": [], "es": []},  # e.g. ["Fully insured", "Techo-Bloc certified installer"]
)

UI = {
 "en": dict(
    lang_name="English", switch_label="Español", switch_short="ES", switch_title="Ver este sitio en español",
    skip="Skip to content", menu="Menu", services_menu="Show services menu",
    nav_home="Home", nav_services="Services", nav_gallery="Gallery", nav_reviews="Reviews",
    nav_about="About", nav_faq="FAQ", nav_join="Join the team", nav_contact="Contact", nav_estimate="Free Estimate", call="Call",
    crumb_label="Breadcrumb", crumb_home="Home", related="Related services",
    common_q="Common questions", more_q="More questions", included="What's included", how_we_work="How we work",
    cta_title="Ready to talk about your project?", cta_text="Tell us what you have in mind. We'll get back to you by text or phone.",
    cta_btn="Request a Free Estimate", about="About", footer_area="Royersford & Chester County, PA",
    privacy="Privacy", back_top="Back to top", before="Before", after="After",
    slider_hint="Drag the handle, or use the arrow keys, to compare each before and after.",
    gallery_cta="Want something like this?", see_more_ba="See more before & afters",
    google_label="Reviews from Google", rating_sr="Rated 5.0 out of 5 stars on Google", google_btn="Read all reviews on Google", write_btn="Leave a review on Google", see_all="See all reviews", anon_reviewer="Google review", view_on_google="View on Google",
    reviews_orig="",
    sticky_call="Call Now", join_link="Join the team",
 ),
 "es": dict(
    lang_name="Español", switch_label="English", switch_short="EN", switch_title="View this site in English",
    skip="Saltar al contenido", menu="Menú", services_menu="Mostrar menú de servicios",
    nav_home="Inicio", nav_services="Servicios", nav_gallery="Galería", nav_reviews="Reseñas",
    nav_about="Nosotros", nav_faq="Preguntas", nav_join="Únase al equipo", nav_contact="Contacto", nav_estimate="Cotización gratis", call="Llamar",
    crumb_label="Ruta de navegación", crumb_home="Inicio", related="Servicios relacionados",
    common_q="Preguntas frecuentes", more_q="Más preguntas", included="Qué incluye", how_we_work="Cómo trabajamos",
    cta_title="¿Listo para hablar de su proyecto?", cta_text="Cuéntenos qué tiene en mente. Le respondemos por mensaje de texto o llamada.",
    cta_btn="Solicitar cotización gratis", about="Más sobre", footer_area="Royersford y el condado de Chester, PA",
    privacy="Privacidad", back_top="Volver arriba", before="Antes", after="Después",
    slider_hint="Arrastre el control, o use las flechas del teclado, para comparar el antes y el después.",
    gallery_cta="¿Quiere algo así?", see_more_ba="Ver más antes y después",
    google_label="Reseñas de Google", rating_sr="Calificación de 5.0 sobre 5 estrellas en Google", google_btn="Leer todas las reseñas en Google", write_btn="Dejar una reseña en Google", see_all="Ver todas las reseñas", anon_reviewer="Reseña de Google", view_on_google="Ver en Google",
    reviews_orig="Reseñas originales en inglés, tal como las escribieron nuestros clientes.",
    sticky_call="Llamar ahora", join_link="Únase al equipo",
 ),
}

# ---------------------------------------------------------------- services
SERVICES = [
 dict(slug="lawn-care", related=["seasonal-cleanup", "sod-seeding", "landscape-design"],
  en=dict(name="Lawn Care & Maintenance", tag="Mowing and upkeep, handled on schedule.",
   title="Lawn Mowing & Lawn Care in Royersford, PA",
   desc="Lawn mowing service, trimming and groundskeeping in Royersford and Chester County. A professional, friendly crew and fair pricing.",
   intro=["A good lawn doesn't take magic. It takes someone who shows up when they say they will and does the job right every time. That's what we aim for on every yard we take care of.",
          "We handle regular mowing and trimming, ongoing groundskeeping, and the small stuff that keeps a property looking cared for. If the weather pushes your day, we text you and reschedule. You shouldn't have to chase us."],
   includes=["Lawn mowing and edging", "String trimming around beds, fences and trees", "Blowing off driveways, walks and patios", "Groundskeeping and general yard work", "Ongoing landscape management for your property"],
   how=[("Tricky yard? No problem.", "Slopes, tight gates and odd corners are part of the job. We'll look at your lawn first and tell you what to expect."),
        ("We keep you in the loop.", "Weather delay or schedule change? You'll hear from us before we're late, not after."),
        ("Simple, fair pricing.", "You get a clear price up front, based on your actual property.")],
   faq=[("Do you offer a lawn mowing service in Royersford?", "Yes. We mow and maintain lawns in Royersford and the surrounding Chester County area. [Send a request](contact) and we'll tell you if we cover your address."),
        ("How often will you mow?", "Most customers choose weekly or every other week during the growing season. We'll suggest what fits your lawn and budget."),
        ("Do I have to be home?", "No. As long as we can get to the lawn, we'll do the work and let you know when we're finished."),
        ("Can you take care of leaves in the fall?", "Yes. See our [seasonal cleanup](seasonal-cleanup) service.")]),
  es=dict(name="Cuidado del césped y mantenimiento", tag="Corte y mantenimiento, siempre a tiempo.",
   title="Corte de césped y cuidado del jardín en Royersford, PA",
   desc="Servicio de corte de césped, recorte y mantenimiento de jardines en Royersford y el condado de Chester. Un equipo profesional y amable, y precios justos.",
   intro=["Un buen césped no requiere magia. Requiere a alguien que llegue cuando dice que va a llegar y haga bien el trabajo cada vez. Eso es lo que buscamos en cada jardín que cuidamos.",
          "Hacemos el corte y recorte regular, el mantenimiento continuo y los pequeños detalles que mantienen su propiedad bien cuidada. Si el clima cambia su día, le enviamos un mensaje y reprogramamos. No tiene que perseguirnos."],
   includes=["Corte de césped y bordes", "Recorte con orilladora alrededor de camas, cercas y árboles", "Soplado de entradas, aceras y patios", "Mantenimiento del jardín y trabajo general", "Manejo continuo del paisaje de su propiedad"],
   how=[("¿Un jardín difícil? No hay problema.", "Las pendientes, los portones angostos y las esquinas raras son parte del trabajo. Primero vemos su césped y le decimos qué esperar."),
        ("Lo mantenemos informado.", "¿Retraso por el clima o cambio de horario? Sabrá de nosotros antes de llegar tarde, no después."),
        ("Precios simples y justos.", "Recibe un precio claro de antemano, basado en su propiedad real.")],
   faq=[("¿Ofrecen servicio de corte de césped en Royersford?", "Sí. Cortamos y mantenemos céspedes en Royersford y el área cercana del condado de Chester. [Envíe una solicitud](contact) y le diremos si cubrimos su dirección."),
        ("¿Cada cuánto cortan el césped?", "La mayoría de los clientes eligen cada semana o cada dos semanas durante la temporada de crecimiento. Le sugeriremos lo que mejor se ajuste a su césped y presupuesto."),
        ("¿Tengo que estar en casa?", "No. Mientras podamos llegar al césped, hacemos el trabajo y le avisamos cuando terminamos."),
        ("¿Pueden encargarse de las hojas en otoño?", "Sí. Vea nuestro servicio de [limpieza de temporada](seasonal-cleanup).")])),

 dict(slug="landscape-design", related=["hardscaping", "lawn-care", "seasonal-cleanup"],
  en=dict(name="Landscape Design & Installation", tag="Beds, borders and plantings that fit how you live.",
   title="Landscape Design & Installation in Royersford, PA",
   desc="Garden design, new beds, mulch and plantings in Royersford and Chester County. Owner-operated and easy to work with.",
   intro=["Some yards just need a fresh start. Overgrown beds, tired ground cover, a corner nobody knows what to do with. We help you decide what should stay, what should go, and what would make the space work better.",
          "Then we build it. New beds, mulch, plantings, relocating shrubs, finishing touches. We keep the job site neat and the plan simple, so you see the result you pictured."],
   includes=["Garden and landscape design", "New planting beds and borders", "Mulching and weed control", "Removing old ground cover and overgrowth", "Relocating and planting shrubs, flowers and trees", "Garden decorating and finishing touches"],
   how=[("We listen first.", "Tell us what you want and what bugs you about the space. We design around that, not a template."),
        ("Work that stays on budget.", "We agree on the plan and the price before we start, then stick to it."),
        ("Clean and tidy.", "We clear our mess as we go and leave the area ready to enjoy.")],
   faq=[("Do you do small projects?", "Yes. A single bed or a corner redo is just as welcome as a bigger job."),
        ("Can you work with plants I already have?", "Often, yes. We're happy to save and relocate what's worth keeping."),
        ("When is the best time to plant?", "Spring and fall are usually best. We'll talk timing when we see your yard."),
        ("Can you also build walls or walkways for the design?", "Yes. See [hardscaping](hardscaping) and [retaining walls](retaining-walls).")]),
  es=dict(name="Diseño e instalación de paisajes", tag="Camas, bordes y plantas que se adaptan a su forma de vivir.",
   title="Diseño e instalación de paisajismo en Royersford, PA",
   desc="Diseño de jardines, camas nuevas, mantillo y plantas en Royersford y el condado de Chester. Negocio familiar y fácil de trabajar.",
   intro=["Algunos jardines solo necesitan un nuevo comienzo. Camas descuidadas, cubresuelos cansados, una esquina que nadie sabe qué hacer con ella. Le ayudamos a decidir qué se queda, qué se va y qué haría que el espacio funcione mejor.",
          "Luego lo construimos. Camas nuevas, mantillo, plantas, traslado de arbustos y detalles finales. Mantenemos el lugar de trabajo limpio y el plan simple, para que vea el resultado que imaginó."],
   includes=["Diseño de jardines y paisajes", "Camas y bordes de plantas nuevos", "Mantillo y control de maleza", "Retiro de cubresuelos viejos y maleza", "Traslado y siembra de arbustos, flores y árboles", "Decoración del jardín y detalles finales"],
   how=[("Primero escuchamos.", "Cuéntenos qué quiere y qué le molesta del espacio. Diseñamos a partir de eso, no de una plantilla."),
        ("Trabajo que respeta el presupuesto.", "Acordamos el plan y el precio antes de empezar, y lo cumplimos."),
        ("Limpio y ordenado.", "Limpiamos mientras trabajamos y dejamos el área lista para disfrutar.")],
   faq=[("¿Hacen proyectos pequeños?", "Sí. Una sola cama o una esquina es tan bienvenida como un trabajo más grande."),
        ("¿Pueden trabajar con las plantas que ya tengo?", "Muchas veces sí. Con gusto conservamos y trasladamos lo que vale la pena."),
        ("¿Cuándo es el mejor momento para sembrar?", "La primavera y el otoño suelen ser lo mejor. Hablaremos del momento adecuado cuando veamos su jardín."),
        ("¿También pueden construir muros o caminos para el diseño?", "Sí. Vea [hardscaping](hardscaping) y [muros de contención](retaining-walls).")])),

 dict(slug="hardscaping", related=["retaining-walls", "landscape-design", "drainage-grading"],
  en=dict(name="Hardscaping", tag="Stone, steps and walkways built to last.",
   title="Hardscaping, Walkways & Stone in Royersford, PA",
   desc="Walkway and driveway paving, outdoor steps, and stone and rock landscaping in Royersford and Chester County.",
   intro=["Hardscaping is the part of your yard that has to hold up. People walk on it, cars drive over it, and Pennsylvania weather tests it every year. So we focus on a solid base and careful finish work, because that's what you can't see and what matters most.",
          "Whether you want a better path to the front door, safer steps, or stone that gives a bed some character, we'll talk it through and give you a straight answer on what makes sense."],
   includes=["Driveway and walkway paving", "Outdoor step construction", "Stone and rock landscaping", "Walkway and driveway landscaping", "General hardscape repair and upgrades"],
   how=[("Built from the ground up.", "A good surface starts with good prep. We don't skip the steps you can't see."),
        ("Options for your budget.", "There's more than one way to build a walkway. We'll show you the choices and what they cost."),
        ("Fits your home.", "Straight or curved, formal or relaxed, we match the style of your property.")],
   faq=[("How much does a paver walkway cost?", "It depends on the length, width, materials and how much prep your site needs. We look at the space and give you a clear price before any work starts. [Request a free estimate](contact)."),
        ("Can you add steps to a sloped yard?", "Yes. Steps and retaining walls often go together on a slope. See our [retaining walls](retaining-walls) page."),
        ("How long does a walkway take?", "It depends on size and conditions. We'll give you a realistic timeline with your estimate."),
        ("Can you match the stone I already have?", "We'll do our best. Send us a photo and we'll talk it through.")]),
  es=dict(name="Hardscaping (piedra y pavimentos)", tag="Piedra, escalones y caminos hechos para durar.",
   title="Hardscaping, caminos y piedra en Royersford, PA",
   desc="Pavimentación de caminos y entradas, escalones exteriores y paisajismo con piedra en Royersford y el condado de Chester.",
   intro=["El hardscaping es la parte de su jardín que tiene que aguantar. La gente camina sobre él, los autos pasan por encima y el clima de Pennsylvania lo pone a prueba cada año. Por eso nos enfocamos en una base sólida y un acabado cuidadoso, porque es lo que no se ve y lo que más importa.",
          "Ya sea que quiera un mejor camino a la puerta principal, escalones más seguros o piedra que le dé carácter a una cama, lo conversamos y le damos una respuesta sincera sobre lo que tiene sentido."],
   includes=["Pavimentación de entradas y caminos", "Construcción de escalones exteriores", "Paisajismo con piedra y roca", "Paisajismo de caminos y entradas", "Reparación y mejoras generales de hardscape"],
   how=[("Construido desde la base.", "Una buena superficie empieza con una buena preparación. No nos saltamos los pasos que no se ven."),
        ("Opciones para su presupuesto.", "Hay más de una forma de construir un camino. Le mostramos las opciones y lo que cuestan."),
        ("Va con su casa.", "Recto o curvo, formal o relajado, adaptamos el estilo a su propiedad.")],
   faq=[("¿Cuánto cuesta un camino de adoquines?", "Depende del largo, el ancho, los materiales y cuánta preparación necesite su terreno. Vemos el espacio y le damos un precio claro antes de empezar. [Solicite una cotización gratis](contact)."),
        ("¿Pueden agregar escalones en un terreno inclinado?", "Sí. Los escalones y los muros de contención suelen ir juntos en una pendiente. Vea nuestra página de [muros de contención](retaining-walls)."),
        ("¿Cuánto tarda un camino?", "Depende del tamaño y las condiciones. Le daremos un tiempo realista con su cotización."),
        ("¿Pueden igualar la piedra que ya tengo?", "Haremos lo posible. Envíenos una foto y lo conversamos.")])),

 dict(slug="retaining-walls", related=["drainage-grading", "hardscaping", "landscape-design"],
  en=dict(name="Retaining Walls", tag="Solve the slope. Add the structure.",
   title="Retaining Walls in Royersford, PA",
   desc="Retaining wall construction in Royersford and Chester County. Level your yard, control slopes and add lasting structure.",
   intro=["A slope can cause real headaches: washed-out soil, a yard you can't use, or a bed that won't hold together. A well-built retaining wall fixes the problem and can make the whole yard look better.",
          "We build walls that do their job first. Then we make sure they look good doing it."],
   includes=["Retaining wall construction", "Stone and block walls", "Walls combined with steps", "Leveling and shaping slopes for usable space", "Drainage planning so the wall holds up"],
   how=[("We look at the whole slope.", "Water, soil and weight all matter. We plan for them before we build."),
        ("Drainage comes first.", "A wall that can't drain won't last. We build with water in mind."),
        ("Straight talk on cost.", "We'll explain what drives the price and what your options are.")],
   faq=[("How much does a retaining wall cost?", "It depends on the wall's length and height, the material, and how easy your site is to reach. We'll look at your slope and give you a clear price before work starts. [Request a free estimate](contact)."),
        ("Do I need a wall or just grading?", "Sometimes regrading is enough. We'll tell you honestly which one fits. See [drainage and grading](drainage-grading)."),
        ("Can a wall make my yard more usable?", "Yes. Walls can turn a steep slope into a flat area you can use."),
        ("Can steps be built into the wall?", "Yes, and it's a common way to connect upper and lower areas. See [hardscaping](hardscaping).")]),
  es=dict(name="Muros de contención", tag="Resuelva la pendiente. Agregue estructura.",
   title="Muros de contención en Royersford, PA",
   desc="Construcción de muros de contención en Royersford y el condado de Chester. Nivele su terreno, controle las pendientes y agregue estructura duradera.",
   intro=["Una pendiente puede causar verdaderos dolores de cabeza: tierra que se lava, un jardín que no se puede usar o una cama que no se sostiene. Un muro de contención bien construido resuelve el problema y puede mejorar la apariencia de todo el jardín.",
          "Construimos muros que primero cumplan su función. Luego nos aseguramos de que además se vean bien."],
   includes=["Construcción de muros de contención", "Muros de piedra y bloque", "Muros combinados con escalones", "Nivelación y modelado de pendientes para tener espacio útil", "Planificación del drenaje para que el muro dure"],
   how=[("Miramos toda la pendiente.", "El agua, la tierra y el peso importan. Los planeamos antes de construir."),
        ("El drenaje va primero.", "Un muro que no drena no dura. Construimos pensando en el agua."),
        ("Hablamos claro del costo.", "Le explicamos qué determina el precio y cuáles son sus opciones.")],
   faq=[("¿Cuánto cuesta un muro de contención?", "Depende del largo y la altura del muro, el material y qué tan fácil sea llegar a su terreno. Veremos su pendiente y le daremos un precio claro antes de empezar. [Solicite una cotización gratis](contact)."),
        ("¿Necesito un muro o solo nivelación?", "A veces basta con nivelar de nuevo. Le diremos con honestidad cuál conviene. Vea [drenaje y nivelación](drainage-grading)."),
        ("¿Un muro puede hacer mi jardín más útil?", "Sí. Los muros pueden convertir una pendiente fuerte en un área plana que puede usar."),
        ("¿Se pueden construir escalones dentro del muro?", "Sí, y es una forma común de conectar las áreas alta y baja. Vea [hardscaping](hardscaping).")])),

 dict(slug="drainage-grading", related=["retaining-walls", "sod-seeding", "hardscaping"],
  en=dict(name="Drainage & Grading", tag="Move the water. Protect the yard.",
   title="Yard Drainage & Grading in Royersford, PA",
   desc="Fix yard drainage problems, standing water and soggy spots with grading and resloping in Royersford and Chester County.",
   intro=["Standing water, soggy patches and soil washing toward the house are signs your yard isn't draining the way it should. The good news is that most of these problems can be fixed.",
          "We look at how water actually moves across your property, then regrade or reshape the ground to send it where it should go."],
   includes=["Yard drainage solutions", "Yard grading", "Grading and resloping", "Reshaping the ground away from the house", "Prep work for lawns, beds and hardscape"],
   how=[("See it in action.", "If you can, show us the problem area after rain. It helps us fix the right thing."),
        ("Fix the cause.", "We aim to solve the problem, not cover it up."),
        ("Ready for what's next.", "Once the ground is right, we can seed, sod or plant the area.")],
   faq=[("How do I fix yard drainage problems?", "Start by finding where the water collects and where it comes from. Often the fix is regrading so water moves away from the house, sometimes with a wall or other drainage work. We'll look at your yard and tell you what makes sense. [Request a free estimate](contact)."),
        ("Why is my yard always wet?", "Usually it's low spots, poor slope or compacted soil. We'll check on site."),
        ("Can you grade and then reseed?", "Yes. We can take it from rough ground to finished lawn. See [aeration, sod and seeding](sod-seeding)."),
        ("Do you work on small problem areas?", "Yes. Many jobs are a single low spot or one side of the house.")]),
  es=dict(name="Drenaje y nivelación", tag="Dirija el agua. Proteja su jardín.",
   title="Drenaje y nivelación de jardines en Royersford, PA",
   desc="Solucione problemas de drenaje, agua estancada y zonas encharcadas con nivelación del terreno en Royersford y el condado de Chester.",
   intro=["El agua estancada, las zonas empapadas y la tierra que se lava hacia la casa son señales de que su jardín no drena como debería. La buena noticia es que la mayoría de estos problemas tienen solución.",
          "Observamos cómo se mueve realmente el agua por su propiedad y luego nivelamos o damos forma al terreno para llevarla adonde debe ir."],
   includes=["Soluciones de drenaje para jardines", "Nivelación del terreno", "Nivelación y cambio de pendiente", "Dar forma al terreno para alejar el agua de la casa", "Preparación para césped, camas y hardscape"],
   how=[("Véalo en acción.", "Si puede, muéstrenos la zona problemática después de la lluvia. Nos ayuda a arreglar lo correcto."),
        ("Arreglamos la causa.", "Buscamos resolver el problema, no taparlo."),
        ("Listo para lo que sigue.", "Cuando el terreno está bien, podemos sembrar, poner césped en rollo o plantar el área.")],
   faq=[("¿Cómo soluciono los problemas de drenaje en mi jardín?", "Primero hay que encontrar dónde se acumula el agua y de dónde viene. Muchas veces la solución es nivelar de nuevo para que el agua se aleje de la casa, a veces con un muro u otro trabajo de drenaje. Veremos su jardín y le diremos qué conviene. [Solicite una cotización gratis](contact)."),
        ("¿Por qué mi jardín siempre está mojado?", "Por lo general son zonas bajas, mala pendiente o tierra compactada. Lo revisaremos en el lugar."),
        ("¿Pueden nivelar y luego sembrar césped?", "Sí. Podemos llevarlo de terreno áspero a césped terminado. Vea [aireación, césped y siembra](sod-seeding)."),
        ("¿Trabajan en áreas problemáticas pequeñas?", "Sí. Muchos trabajos son un solo punto bajo o un lado de la casa.")])),

 dict(slug="sod-seeding", related=["lawn-care", "drainage-grading", "seasonal-cleanup"],
  en=dict(name="Aeration, Sod & Seeding", tag="A healthier lawn, from the roots up.",
   title="Lawn Aeration, Overseeding & Sod in Royersford, PA",
   desc="Core aeration, overseeding, sod installation and grass seeding in Royersford and Chester County. Fix a thin lawn or start a new one.",
   intro=["Starting a lawn from scratch or repairing a thin, patchy one comes down to good prep. Get the ground ready and the right grass in, and the rest gets easier.",
          "Seed costs less and takes patience. Sod gives you a green lawn right away. We'll help you choose, then do the work."],
   includes=["Core lawn aeration", "Overseeding and top dressing", "Sod installation", "Grass seeding", "Ground prep and grading", "Lawn landscaping and repair", "Follow-up advice so your new lawn takes hold"],
   how=[("Prep matters most.", "We get the ground ready before anything goes down."),
        ("Seed or sod?", "We'll explain the tradeoffs in time, cost and results so you can pick."),
        ("Tell you what to do next.", "New lawns need care. We'll tell you what to expect.")],
   faq=[("How soon can I use my new lawn?", "It depends on seed or sod and the weather. We'll go over it before we start."),
        ("When should I seed?", "Early fall is often a good window. Spring can work too. We'll recommend timing for your yard."),
        ("Can you fix just part of my lawn?", "Yes. Patching bare areas is a common job."),
        ("Does the ground need work first?", "Often it does. See [drainage and grading](drainage-grading)."),
        ("When is the best time to aerate?", "Spring and especially fall. We recommend aerating at least once a year, and fall is the ideal time to combine it with overseeding."),
        ("Do I need to pick up the soil plugs?", "No. Leave them. They break down over the next week or two and work back into the soil.")],
   extra=[
    ("Why aerate your lawn?",
     ["Aeration is one of the most useful things you can do to keep a lawn healthy and head off problems. Compacted soil and heavy thatch are the two biggest obstacles to a good-looking lawn, and aeration tackles both.",
      "The small cores you see on the lawn afterward break down over the next week or two. That natural return to the soil helps keep thatch at a healthy level. It works best as a regular part of your lawn care, not a one-time fix."],
     ["Improves drainage", "Gets more air, water and nutrients down to the roots", "Relieves soil compaction", "Stimulates new growth", "Reduces thatch build-up", "Helps water reach thirsty roots during dry spells", "Creates a better bed for overseeding", "Makes fertilizer work better"],
     "Spring and especially fall are the best times to aerate. We recommend doing it at least once a year. It's a relatively low-cost service that makes a real difference in how your turf looks."),
    ("Why overseed?",
     ["Overseeding fills in the thin areas where grass has died off. We can top dress, aerate and overseed your lawn so it comes back thicker, greener and healthier.",
      "Your lawn is at its best for taking seed right after aeration, which is why the two jobs go together so well. It's a simple, affordable two-step process that can help even a stressed lawn, including one worn down by too much rain or a dry summer. Aerating and overseeding in the fall sets your Royersford and Chester County lawn up for a healthy summer next year."],
     [], ""),
    ("After care: aeration and overseeding",
     ["Once your lawn has been aerated and overseeded, how you care for it makes a big difference. Here's what we tell our customers."],
     [], ""),
   ],
   aftercare=[
    ("Leave the soil plugs", "Let them break down on the lawn and fall back into the holes. If you seeded, the seed mixes in with the loosened soil. Your mower will often break the plugs up within two to three weeks."),
    ("Keep it moist for 3 weeks", "Water the seed in right away. For the first three weeks keep the surface damp, not soaking wet. You'll start to see grass sprouting from the holes. For the next three weeks, water more thoroughly but less often. Early morning is best."),
    ("Limit traffic", "Keep foot traffic to a minimum, pets included. Staying off the lawn for the first few weeks gives the seed a better chance to take."),
    ("Mow carefully", "Mowing weekly is fine once the seed is well watered in and the grass is about 4 inches tall. Use a sharp blade for a clean cut that won't pull up new seedlings, and take off no more than one third of the blade height each time. Leave the clippings. They can hold some seed."),
    ("Go easy with fall leaves", "Seedlings are delicate with shallow roots. Raking tears them up. Lightly blow the leaves off, or mulch them with the mower."),
   ]),
  es=dict(name="Aireación, césped en rollo y siembra", tag="Un césped más sano, desde las raíces.",
   title="Aireación, resiembra y césped en rollo en Royersford, PA",
   desc="Aireación del césped, resiembra, instalación de césped en rollo y siembra de pasto en Royersford y el condado de Chester. Repare un césped ralo o empiece uno nuevo.",
   intro=["Empezar un césped desde cero o reparar uno ralo y con parches depende de una buena preparación. Prepare el terreno y ponga el pasto adecuado, y todo lo demás es más fácil.",
          "La semilla cuesta menos y requiere paciencia. El césped en rollo le da un césped verde de inmediato. Le ayudamos a elegir y luego hacemos el trabajo."],
   includes=["Aireación de césped", "Resiembra y capa de tierra (top dressing)", "Instalación de césped en rollo (sod)", "Siembra de pasto", "Preparación y nivelación del terreno", "Paisajismo y reparación de césped", "Consejos de seguimiento para que su césped nuevo prenda"],
   how=[("La preparación es lo más importante.", "Dejamos el terreno listo antes de poner cualquier cosa."),
        ("¿Semilla o césped en rollo?", "Le explicamos las diferencias de tiempo, costo y resultado para que elija."),
        ("Le decimos qué hacer después.", "Los céspedes nuevos necesitan cuidado. Le diremos qué esperar.")],
   faq=[("¿Cuándo puedo usar mi césped nuevo?", "Depende de si es semilla o césped en rollo y del clima. Lo revisamos antes de empezar."),
        ("¿Cuándo debo sembrar?", "El inicio del otoño suele ser una buena época. La primavera también puede funcionar. Le recomendaremos el momento para su jardín."),
        ("¿Pueden arreglar solo una parte de mi césped?", "Sí. Rellenar zonas sin pasto es un trabajo común."),
        ("¿El terreno necesita trabajo primero?", "Muchas veces sí. Vea [drenaje y nivelación](drainage-grading)."),
        ("¿Cuándo es mejor airear?", "En primavera y, sobre todo, en otoño. Recomendamos airear al menos una vez al año, y el otoño es ideal para combinarlo con la resiembra."),
        ("¿Tengo que recoger los tapones de tierra?", "No. Déjelos. Se deshacen en una o dos semanas y vuelven al suelo.")],
   extra=[
    ("¿Por qué airear su césped?",
     ["La aireación es una de las mejores cosas que puede hacer para mantener sano su césped y evitar problemas. La tierra compactada y el exceso de fieltro (thatch) son los dos mayores obstáculos para un césped bonito, y la aireación ataca ambos.",
      "Los pequeños tapones de tierra que verá en el césped después se deshacen en una o dos semanas. Ese regreso natural al suelo ayuda a mantener el fieltro en un nivel saludable. Funciona mejor como parte regular del cuidado de su césped, no como un arreglo de una sola vez."],
     ["Mejora el drenaje", "Lleva más aire, agua y nutrientes a las raíces", "Alivia la compactación del suelo", "Estimula el crecimiento nuevo", "Reduce la acumulación de fieltro", "Ayuda a que el agua llegue a las raíces durante las sequías", "Crea una mejor base para la resiembra", "Hace que el fertilizante funcione mejor"],
     "La primavera y, sobre todo, el otoño son las mejores épocas para airear. Recomendamos hacerlo al menos una vez al año. Es un servicio de costo relativamente bajo que marca una diferencia real en el aspecto de su césped."),
    ("¿Por qué resembrar?",
     ["La resiembra rellena las zonas ralas donde el pasto se ha secado. Podemos aplicar tierra superficial (top dressing), airear y resembrar para que su césped vuelva más espeso, verde y sano.",
      "Su césped está en el mejor momento para recibir semilla justo después de airear, por eso los dos trabajos van tan bien juntos. Es un proceso sencillo y económico de dos pasos que puede ayudar incluso a un césped estresado, por ejemplo por exceso de lluvia o un verano seco. Airear y resembrar en otoño prepara su césped en Royersford y el condado de Chester para un verano sano el año siguiente."],
     [], ""),
    ("Cuidados después de airear y resembrar",
     ["Después de airear y resembrar, la forma en que cuide su césped hace una gran diferencia. Esto es lo que les decimos a nuestros clientes."],
     [], ""),
   ],
   aftercare=[
    ("Deje los tapones de tierra", "Deje que se deshagan sobre el césped y vuelvan a caer en los huecos. Si sembró, la semilla se mezcla con la tierra suelta. La podadora suele deshacer los tapones en dos o tres semanas."),
    ("Mantenga la humedad 3 semanas", "Riegue la semilla de inmediato. Durante las primeras tres semanas mantenga la superficie húmeda, no empapada. Verá brotar pasto de los huecos. Durante las siguientes tres semanas, riegue más a fondo pero con menos frecuencia. Lo mejor es temprano por la mañana."),
    ("Limite el paso", "Reduzca al mínimo el tránsito a pie, incluidas las mascotas. Mantenerse fuera del césped las primeras semanas le da a la semilla mejor oportunidad de germinar."),
    ("Corte con cuidado", "Puede cortar cada semana cuando la semilla esté bien regada y el pasto mida unas 4 pulgadas. Use una cuchilla afilada para un corte limpio que no arranque las plántulas, y quite no más de un tercio de la altura cada vez. Deje los recortes. Pueden contener algo de semilla."),
    ("Cuidado con las hojas de otoño", "Las plántulas son delicadas y tienen raíces poco profundas. Rastrillar las arranca. Sople las hojas suavemente o tritúrelas con la podadora."),
   ])),

 dict(slug="seasonal-cleanup", related=["lawn-care", "landscape-design", "tree-snow"],
  en=dict(name="Seasonal Cleanup", tag="Spring and fall resets, leaves hauled away.",
   title="Spring & Fall Cleanup, Leaf Removal in Royersford, PA",
   desc="Spring and fall yard cleanup and leaf collection in Royersford and Chester County. We haul it away.",
   intro=["Leaves pile up, beds get messy, and winter leaves a mess behind. A seasonal cleanup resets your yard so it's ready for the months ahead.",
          "We do the raking, collecting and hauling so you don't have to."],
   includes=["Leaf collection and disposal", "Spring and fall yard cleanup", "Bed cleanup and mulching", "Weed control", "General yard work"],
   how=[("We take it with us.", "Cleanup includes hauling the debris away."),
        ("Good timing.", "We'll help you pick the right week so it's done once and done well."),
        ("Easy to add on.", "If we already mow your lawn, cleanup is simple to schedule.")],
   faq=[("When should I book a fall cleanup?", "Once most of the leaves are down. Send a request early and we'll plan with you."),
        ("Do you mulch beds in spring?", "Yes. See [landscape design](landscape-design)."),
        ("Can you do a one-time cleanup?", "Yes. You don't need to be a regular customer.")]),
  es=dict(name="Limpieza de temporada", tag="Limpieza de primavera y otoño, hojas retiradas.",
   title="Limpieza de primavera y otoño y retiro de hojas en Royersford, PA",
   desc="Limpieza de jardín y recolección de hojas en primavera y otoño en Royersford y el condado de Chester. Nos llevamos todo.",
   intro=["Las hojas se acumulan, las camas se ensucian y el invierno deja desorden. Una limpieza de temporada renueva su jardín para los meses que vienen.",
          "Nosotros rastrillamos, recogemos y nos llevamos todo para que usted no tenga que hacerlo."],
   includes=["Recolección y retiro de hojas", "Limpieza de jardín en primavera y otoño", "Limpieza de camas y mantillo", "Control de maleza", "Trabajo general de jardín"],
   how=[("Nos lo llevamos.", "La limpieza incluye retirar los desechos."),
        ("Buen momento.", "Le ayudamos a elegir la semana correcta para hacerlo una vez y bien."),
        ("Fácil de agregar.", "Si ya cortamos su césped, es sencillo programar la limpieza.")],
   faq=[("¿Cuándo debo reservar la limpieza de otoño?", "Cuando ya haya caído la mayoría de las hojas. Envíe una solicitud con tiempo y planeamos con usted."),
        ("¿Ponen mantillo en las camas en primavera?", "Sí. Vea [diseño de paisajes](landscape-design)."),
        ("¿Pueden hacer una limpieza única?", "Sí. No necesita ser cliente regular.")])),

 dict(slug="tree-snow", related=["seasonal-cleanup", "lawn-care", "hardscaping"],
  en=dict(name="Tree Work & Snow Removal", tag="Property care when conditions get rough.",
   title="Tree Work & Snow Removal in Royersford, PA",
   desc="Tree work and snow removal in Royersford and Chester County. Local, owner-operated and responsive.",
   intro=["Some jobs don't wait for a convenient day. A tree that needs attention or a driveway buried in snow is a problem you want solved fast by someone you can reach.",
          "We handle tree work and winter snow removal for homes and properties around Royersford, with the same communication you'd expect from us the rest of the year."],
   includes=["Tree work and tree landscaping", "Property maintenance through the seasons", "Snow removal for driveways and walkways"],
   how=[("Tell us what's going on.", "A quick photo and a description help us plan before we get there."),
        ("Winter service you can count on.", "If you want snow service, contact us before the season starts so we can plan your property."),
        ("Safety first.", "We'll tell you honestly if a job needs a different kind of specialist.")],
   faq=[("How do I sign up for snow removal?", "[Send a request](contact) or call us. We'll talk through your property and options."),
        ("Do you take on large trees?", "Contact us with details and photos. We'll tell you whether it's a fit."),
        ("Can I combine services?", "Yes. Many customers pair [lawn care](lawn-care) in summer with snow service in winter.")]),
  es=dict(name="Trabajo con árboles y remoción de nieve", tag="Cuidado de su propiedad cuando el clima se complica.",
   title="Trabajo con árboles y remoción de nieve en Royersford, PA",
   desc="Trabajo con árboles y remoción de nieve en Royersford y el condado de Chester. Negocio local, familiar y atento.",
   intro=["Algunos trabajos no esperan a un día conveniente. Un árbol que necesita atención o una entrada cubierta de nieve es un problema que quiere resolver rápido con alguien a quien pueda contactar.",
          "Hacemos trabajo con árboles y remoción de nieve en invierno para casas y propiedades alrededor de Royersford, con la misma comunicación que espera de nosotros el resto del año."],
   includes=["Trabajo con árboles y paisajismo con árboles", "Mantenimiento de la propiedad durante todo el año", "Remoción de nieve de entradas y caminos"],
   how=[("Cuéntenos qué pasa.", "Una foto rápida y una descripción nos ayudan a planear antes de llegar."),
        ("Servicio de invierno confiable.", "Si quiere servicio de nieve, contáctenos antes de que empiece la temporada para planear su propiedad."),
        ("La seguridad primero.", "Le diremos con honestidad si un trabajo necesita otro tipo de especialista.")],
   faq=[("¿Cómo me inscribo para la remoción de nieve?", "[Envíe una solicitud](contact) o llámenos. Conversaremos sobre su propiedad y sus opciones."),
        ("¿Se encargan de árboles grandes?", "Contáctenos con detalles y fotos. Le diremos si podemos hacerlo."),
        ("¿Puedo combinar servicios?", "Sí. Muchos clientes combinan el [cuidado del césped](lawn-care) en verano con el servicio de nieve en invierno.")])),
]

# ---------------------------------------------------------------- gallery shots
SHOTS = [
 dict(key="wall", link="retaining-walls",
  en=dict(title="Retaining wall and planting bed", before="Steep, eroded grass slope beside a brick house with bare dirt and weeds", after="The same slope rebuilt with a stone block retaining wall, mulched planting bed and fresh green lawn", linkname="retaining walls"),
  es=dict(title="Muro de contención y cama de plantas", before="Pendiente de césped erosionada junto a una casa de ladrillo, con tierra expuesta y maleza", after="La misma pendiente reconstruida con un muro de contención de bloques de piedra, cama con mantillo y césped verde nuevo", linkname="muros de contención")),
 dict(key="walkway", link="hardscaping",
  en=dict(title="Paver walkway", before="Worn dirt path and patchy lawn leading to a front door", after="The same entry with a paver walkway, crisp edging and a fresh green lawn", linkname="hardscaping"),
  es=dict(title="Camino de adoquines", before="Sendero de tierra desgastado y césped con parches que lleva a la puerta principal", after="La misma entrada con un camino de adoquines, bordes definidos y césped verde nuevo", linkname="hardscaping")),
 dict(key="bed", link="landscape-design",
  en=dict(title="Garden bed redesign", before="Overgrown, weedy garden bed with scraggly shrubs along a house", after="The same bed redone with dark mulch, flowers, a shaped edge and healthy shrubs", linkname="landscape design"),
  es=dict(title="Rediseño de cama de jardín", before="Cama de jardín descuidada y llena de maleza, con arbustos ralos junto a una casa", after="La misma cama rehecha con mantillo oscuro, flores, un borde definido y arbustos sanos", linkname="diseño de paisajes")),
 dict(key="firepit", link="hardscaping",
  en=dict(title="Stone patio and seating wall", before="Bare, patchy slope behind a deck with compacted dirt and weeds", after="The same yard with a round stone paver patio, a curved stone seating wall, a fire pit, a flagstone path and a green lawn", linkname="hardscaping"),
  es=dict(title="Patio de piedra y muro para sentarse", before="Pendiente sin césped detrás de una terraza, con tierra compactada y maleza", after="El mismo patio con un patio redondo de adoquines de piedra, un muro curvo para sentarse, un fogón, un camino de lajas y césped verde", linkname="hardscaping")),
 dict(key="driveway", link="hardscaping",
  en=dict(title="Paver driveway", before="Old cracked and stained concrete driveway in front of a stone and siding house", after="The same driveway replaced with gray pavers, a dark charcoal border and crisp lawn edges", linkname="hardscaping"),
  es=dict(title="Entrada de adoquines", before="Entrada de concreto vieja, agrietada y manchada frente a una casa de piedra", after="La misma entrada reemplazada con adoquines grises, un borde gris oscuro y bordes de césped definidos", linkname="hardscaping")),
 dict(key="stonewall", link="retaining-walls",
  en=dict(title="Stone retaining wall and mulch beds", before="Steep, overgrown grassy bank in front of a house with bare patches and dead shrubs", after="The same bank rebuilt with a tiered stone retaining wall, mulch beds, daffodils and a trimmed hedge", linkname="retaining walls"),
  es=dict(title="Muro de piedra y camas con mantillo", before="Talud empinado y descuidado frente a una casa, con zonas sin pasto y arbustos secos", after="El mismo talud reconstruido con un muro de contención de piedra por niveles, camas con mantillo, narcisos y un seto recortado", linkname="muros de contención")),
 dict(key="perennial", link="landscape-design",
  en=dict(title="Boulder and flower bed", before="Neglected strip beside a house with weeds, bare soil and a few half-buried rocks", after="The same strip as a landscaped bed with boulders, purple salvia, pink peonies, fresh mulch and a curved lawn edge", linkname="landscape design"),
  es=dict(title="Cama de rocas y flores", before="Franja descuidada junto a una casa, con maleza, tierra expuesta y algunas rocas medio enterradas", after="La misma franja convertida en una cama con rocas grandes, salvia morada, peonías rosadas, mantillo nuevo y un borde de césped curvo", linkname="diseño de paisajes")),
 dict(key="sod", link="sod-seeding",
  en=dict(title="New sod lawn", before="Bare backyard dirt with tire ruts and scattered weeds beside a wooden fence", after="The same yard with a fresh, even green sod lawn edge to edge", linkname="aeration, sod and seeding"),
  es=dict(title="Césped nuevo en rollo", before="Patio trasero con tierra expuesta, huellas de llantas y maleza dispersa junto a una cerca de madera", after="El mismo patio con un césped en rollo nuevo, verde y parejo de orilla a orilla", linkname="aireación, césped y siembra")),
 dict(key="patio", link="hardscaping",
  en=dict(title="Bluestone patio with fire pit", before="Worn wooden deck and a thin, patchy lawn behind a dark blue house, with overgrown shrubs and bare gravel", after="The same backyard with a bluestone patio, a fire pit table, white Adirondack chairs, lighting and layered planting beds", linkname="hardscaping"),
  es=dict(title="Patio de piedra azul con fogón", before="Terraza de madera desgastada y césped ralo detrás de una casa azul oscura, con arbustos descuidados y grava expuesta", after="El mismo patio trasero con un patio de piedra azul, una mesa con fogón, sillas Adirondack blancas, iluminación y camas de plantas por capas", linkname="hardscaping")),
 dict(key="pavers", link="hardscaping",
  en=dict(title="Paver patio and garden", before="Thin, weedy lawn running up to a stone-trimmed house with a few old stepping stones and bare soil", after="The same yard with a curved paver patio, a fire pit, a stepping-stone path and full flower beds", linkname="hardscaping"),
  es=dict(title="Patio de adoquines y jardín", before="Césped ralo y con maleza hasta una casa con detalles de piedra, con algunas lajas viejas y tierra expuesta", after="El mismo patio con un patio curvo de adoquines, un fogón, un camino de lajas y camas de flores completas", linkname="hardscaping")),
 dict(key="slope", link="retaining-walls",
  en=dict(title="Curved retaining wall and lawn", before="Dry, patchy slope beside a two-story house with one overgrown shrub and no edging", after="The same slope with a curved stone block retaining wall, layered evergreens and a thick striped lawn", linkname="retaining walls"),
  es=dict(title="Muro de contención curvo y césped", before="Pendiente seca y con parches junto a una casa de dos pisos, con un arbusto descuidado y sin bordes", after="La misma pendiente con un muro de contención curvo de bloques de piedra, siempreverdes por capas y un césped espeso con rayas", linkname="muros de contención")),
 dict(key="newhome", link="landscape-design",
  en=dict(title="New home landscaping", before="Bare graded dirt and gravel in front of a newly built stone-and-siding home", after="The same home with full landscaping: shrubs, boulders, mulch beds, a clean edge and a sod lawn", linkname="landscape design"),
  es=dict(title="Paisajismo para casa nueva", before="Tierra nivelada y grava expuestas frente a una casa nueva de piedra y revestimiento", after="La misma casa con paisajismo completo: arbustos, rocas grandes, camas con mantillo, borde definido y césped en rollo", linkname="diseño de paisajes")),
 dict(key="lighting", link="hardscaping",
  en=dict(title="Entry walkway and lighting", before="Overgrown plants, scattered rock and uneven old stones leading to a dark front entry at dusk", after="The same entry with a wide bluestone walkway and steps, boulder accents, grasses and warm landscape lighting", linkname="hardscaping"),
  es=dict(title="Camino de entrada e iluminación", before="Plantas descuidadas, rocas dispersas y lajas viejas e irregulares hacia una entrada oscura al anochecer", after="La misma entrada con un camino ancho de piedra azul y escalones, rocas decorativas, pastos ornamentales e iluminación cálida", linkname="hardscaping")),
 dict(key="lawn", link="sod-seeding",
  en=dict(title="Lawn renewal", before="Thin lawn with dry spots, weeds and unkempt edges in front of a brick colonial", after="The same lawn thick, green and freshly striped, with crisp edges and a clean bed", linkname="aeration, sod and seeding"),
  es=dict(title="Renovación del césped", before="Césped ralo con zonas secas, maleza y bordes descuidados frente a una casa colonial de ladrillo", after="El mismo césped espeso, verde y recién cortado con rayas, con bordes definidos y una cama limpia", linkname="aireación, césped y siembra")),
]

# ---------------------------------------------------------------- reviews (English originals)
import json as _json, os as _os
_RV = _json.load(open(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "reviews.json"), encoding="utf-8"))
REVIEWS_META = _RV["meta"]
ALL_REVIEWS = _RV["reviews"]                        # every review, shown on the Reviews page
FEATURED = [r for r in ALL_REVIEWS if r.get("featured")]   # shown on the home page

# ---------------------------------------------------------------- general FAQ
FAQ_GEN = {
 "en": [
  ("Getting started", [
    ("How do I get an estimate?", "Fill out the form on our [contact page](contact) or call 610-357-1098. We're notified of every request."),
    ("How fast will you get back to me?", "We'll get back to you by text or phone as soon as we can."),
    ("Is the estimate free?", "Yes. Requesting an estimate costs nothing.")]),
  ("Our company", [
    ("Where do you work?", "Royersford and the surrounding Chester County area. Not sure if we cover your address? Send a request and we'll tell you."),
    ("Who will be doing the work?", "We're owner-operated, so you deal directly with the people on your property."),
    ("What services do you offer?", "[Lawn care](lawn-care), [landscape design](landscape-design), [hardscaping](hardscaping), [retaining walls](retaining-walls), [drainage and grading](drainage-grading), [aeration, sod and seeding](sod-seeding), [seasonal cleanup](seasonal-cleanup), [tree work and snow removal](tree-snow).")]),
  ("Scheduling and weather", [
    ("What happens if weather changes my appointment?", "We'll let you know and reschedule so you aren't left guessing."),
    ("Can I book a one-time job?", "Yes. Many jobs are one-time projects such as a cleanup, a wall or a regrade.")]),
 ],
 "es": [
  ("Cómo empezar", [
    ("¿Cómo obtengo una cotización?", "Llene el formulario de nuestra [página de contacto](contact) o llame al 610-357-1098. Nos avisan de cada solicitud."),
    ("¿Qué tan rápido me responden?", "Le respondemos por mensaje de texto o llamada lo antes posible."),
    ("¿La cotización es gratis?", "Sí. Solicitar una cotización no cuesta nada.")]),
  ("Nuestra empresa", [
    ("¿Dónde trabajan?", "En Royersford y el área cercana del condado de Chester. ¿No sabe si cubrimos su dirección? Envíe una solicitud y le diremos."),
    ("¿Quién hará el trabajo?", "Somos un negocio con dueño al frente, así que trata directamente con las personas que trabajan en su propiedad."),
    ("¿Qué servicios ofrecen?", "[Cuidado del césped](lawn-care), [diseño de paisajes](landscape-design), [hardscaping](hardscaping), [muros de contención](retaining-walls), [drenaje y nivelación](drainage-grading), [aireación, césped y siembra](sod-seeding), [limpieza de temporada](seasonal-cleanup), [árboles y remoción de nieve](tree-snow).")]),
  ("Horarios y clima", [
    ("¿Qué pasa si el clima cambia mi cita?", "Le avisamos y reprogramamos para que no se quede esperando."),
    ("¿Puedo contratar un trabajo único?", "Sí. Muchos trabajos son proyectos únicos, como una limpieza, un muro o una nivelación.")]),
 ],
}

# ---------------------------------------------------------------- page copy
PAGES = {
 "en": dict(
  home_title="Lawn Care, Hardscaping & Landscaping in Royersford, PA",
  home_desc="Owner-operated landscaping in Royersford and Chester County, PA: lawn care, landscape design, hardscaping, retaining walls, drainage, grading and seasonal cleanup. Request a free estimate.",
  eyebrow="Royersford & Chester County, PA",
  h1="Outdoor spaces built right, and a crew that answers.",
  lead="Owner-operated lawn care, landscape design, hardscaping and retaining walls. Clear communication, fair pricing, and a follow-up check when the job is done.",
  proof=[("Owner-operated by Bryan J. Wolf", ""), ("Free", "estimates")],
  trust=["Professional", "Friendly", "Reliable", "Fair pricing", "Beautiful work"],
  services_h="What we do", services_sub="From weekly mowing to a full backyard rebuild, one local team handles it.",
  cards=[("lawn-care", "Lawn Care & Maintenance", "Mowing, trimming, groundskeeping and ongoing landscape management so your property always looks cared for.", ["Lawn mowing & maintenance", "Groundskeeping", "Landscape management", "Gardening services"]),
         ("landscape-design", "Landscape Design & Installation", "Beds, borders, plantings and mulch designed around how you use your yard.", ["Landscape & garden design", "Landscape installations", "Garden decorating", "Tree & yard landscaping"]),
         ("hardscaping", "Hardscaping", "Durable stone and paver work that adds usable space and curb appeal.", ["Driveway & walkway paving", "Outdoor step construction", "Stone & rock landscaping", "Walkway & driveway landscaping"]),
         ("retaining-walls", "Retaining Walls", "Fix slopes with walls built to last.", ["Retaining walls", "Walls with steps", "Leveling slopes"]),
         ("drainage-grading", "Drainage & Grading", "Move water away from your house and fix soggy spots.", ["Yard drainage", "Grading & resloping", "Yard grading"]),
         ("sod-seeding", "Aeration, Sod & Seeding", "Aerate, overseed or start a new lawn with the right prep and materials.", ["Core aeration", "Overseeding", "Sod and seeding"]),
         ("seasonal-cleanup", "Seasonal Cleanup", "Spring cleanups and fall leaf removal.", ["Leaf collection & disposal", "Mulching & weed control"]),
         ("tree-snow", "Tree Work & Snow Removal", "Help when conditions get rough.", ["Tree work", "Snow removal"])],
  work_h="See the difference",
  process_h="How it works",
  steps=[("Request an estimate", "Fill out the short form or call. We get notified right away."),
         ("We get back to you", "By text or phone, with questions or a time to look at your property."),
         ("Clear, fair quote", "You see the scope and price before any work starts."),
         ("Done on time, then a check-in", "We finish what we promised and follow up to make sure you're happy.")],
  reviews_h="What neighbors say",
  area_h="Serving Royersford & Chester County",
  area_p="We work in Royersford and the surrounding area. Not sure if we cover you? Send a request and we'll let you know.",
  why_h="Why homeowners choose us",
  why=["Owner-operated, so you deal with the people doing the work", "Straight answers and prompt follow-up", "Fair pricing, no surprises", "Clean, neat job sites"],
  gallery_title="Gallery: Before & After Ideas", gallery_desc="Before and after landscaping transformations: retaining walls, walkways, patios, driveways, garden beds and new lawns in Royersford and Chester County, PA.",
  gallery_h="Gallery",
  faq_title="FAQ", faq_desc="Answers about estimates, service area, scheduling and services from Wolf's Landscaping Services in Royersford, PA.", faq_h="Frequently asked questions",
  faq_foot="Still have a question?", faq_foot_link="Send us a request",
  reviews_title="Customer Reviews",
  reviews_desc="What customers say about Wolf's Landscaping Services in Royersford and Chester County, PA, from the business's Google reviews.",
  rpage_h="Customer reviews",
  reviews_lead="What our customers say on Google.",
  reviews_note="Reviews are copied from our Google listing as of October 5, 2026. Times are shown the way Google displayed them that day.",
  reviews_partial="Showing {n} of {total} reviews.",
  about_title="About Us: Owner-Operated Landscaping in Royersford, PA",
  about_desc="Wolf's Landscaping Services is an owner-operated landscaping company in Royersford and Chester County, PA. Learn how we work and what customers say.",
  about_h="About Wolf's Landscaping Services",
  about_lead="An owner-operated landscaping crew serving Royersford and Chester County, PA.",
  about_who_h="Who we are",
  about_who=["Wolf's Landscaping Services is an owner-operated landscaping company serving Royersford and the surrounding Chester County area. When you call or send a request, you deal with the people who will actually be working on your property.",
             "We look after lawns and yards week to week, and we build the bigger things too: beds and plantings, walkways and steps, retaining walls, drainage and grading, new lawns, seasonal cleanups, tree work and snow removal."],
  about_work_h="How we work",
  about_values=[("We communicate", "We keep you posted from your first request to the finished job."),
                ("We hold ourselves to our reviews", "Customers on Google describe us as professional, friendly, thorough and cost effective. Those are the standards we aim for on every job."),
                ("Clear, fair pricing", "You get a clear price before any work starts, with no surprises."),
                ("We check back", "After a job we follow up to make sure you're happy with the result.")],
  about_say_h="What customers say",
  about_quotes=[("Extremely professional company.", "Google review"),
                ("I would recommend this service to anyone.", "Google review"),
                ("They went above and beyond.", "Google review")],
  about_owner_h="Meet the owner", about_story_h="Our story", about_creds_h="Credentials",
  contact_title="Contact & Free Estimate", contact_desc="Request a free landscaping estimate from Wolf's Landscaping Services in Royersford and Chester County, PA. Call or send your request by text.", contact_h="Contact & free estimate",
  contact_lead="Tell us about your project. We'll get back to you by text or phone.",
  contact_call="Prefer to talk? Call", contact_miss="Or send your details with the form below and we'll get back to you.",
  join_title="Join the Team: Landscaping Jobs in Royersford, PA",
  join_desc="Work with Wolf's Landscaping Services in Royersford, PA. Tree work, hardscaping, lawn care and snow removal. Call or text to tell us you're interested.",
  join_h="Join the pack",
  join_lead="Wolf's Landscaping Services is owner-operated, and we're always glad to hear from hardworking people in the Royersford and Chester County area.",
  join_poster_alt="Four illustrated wolves in green work clothes, one with a chainsaw, one carrying pavers, one with a string trimmer and one with a snow shovel, under the words Join the Pack",
  join_intro=["Good work takes a good crew. We handle lawns, hardscaping, trees and snow, and the people on our jobs are what make the work look right.",
             "If you take pride in doing a job well and showing up when you say you will, we'd like to hear from you. Tell us which kind of work interests you."],
  join_roles_h="Where you could fit in",
  join_roles=[("Trees", "Tree work and cleanup.", "tree-snow", "trees", "Illustrated wolf in a green hoodie holding a chainsaw"),
              ("Hardscape", "Pavers, walkways, patios and retaining walls.", "hardscaping", "hardscape", "Illustrated wolf in work clothes carrying paver blocks beside a stone wall"),
              ("Lawn", "Mowing, trimming and ongoing lawn care.", "lawn-care", "lawn", "Illustrated wolf in a cap using a string trimmer"),
              ("Snow", "Plowing and shoveling in winter.", "tree-snow", "snow", "Illustrated wolf in a knit hat shoveling snow")],
  join_look_h="What we look for",
  join_look=["You show up on time and ready to work", "You take pride in a clean, finished job", "You work safely and look out for the crew", "You're friendly and straight with customers"],
  join_apply_h="How to apply",
  join_apply_p="Call or text us and tell us your name, the kind of work that interests you and any experience you have. No experience with a particular tool or job? Say so and ask.",
  join_sms="Text us", join_call="Call",
  join_sms_body="Hi Wolf's Landscaping, I'm interested in joining the team. My name is: ",
  join_note="This page is about work with our crew. For a free estimate on your property, use the contact page.",
  visit_h="Our office", visit_p="Find us on Main Street in Royersford.", directions="Get directions", view_map="View on Google Maps",
  form=dict(name="Name", phone="Phone", email="Email (optional)", address="Property address or town", service="Service needed", choose="Choose one…",
            message="Tell us about the project", pref="Best way to reach you", prefs=["Text", "Email", "Phone call"],
            submit="Prepare my request", help="We'll write your request as a text message, then you choose how to send it. Prefer to talk? Call 610-357-1098.",
            ready="Your request is ready.", choose_how="Choose how to send it:", text_btn="Text it to us", copy_btn="Copy message", call_btn="Call us instead",
            note="Nothing is sent until you press Send in your messaging app.", copied="Copied. Paste it into a text or email, or call 610-357-1098.", copyfail="Could not copy automatically. Please call 610-357-1098 instead.",
            hi="Hi Wolf's Landscaping, I'd like a free estimate.", lbl=dict(name="Name", phone="Phone", email="Email", address="Address or town", service="Service needed", pref="Best way to reach me", details="Project details"),
            services=["Lawn care & maintenance", "Landscape design & installation", "Hardscaping (walkway, steps, stone)", "Retaining wall", "Drainage / grading", "Aeration, sod or seeding", "Seasonal cleanup / leaves", "Tree work", "Snow removal", "Other"]),
  privacy_title="Privacy Policy", privacy_desc="How Wolf's Landscaping Services handles information submitted through this website.",
  privacy_h="Privacy Policy",
  privacy=[("h2", "What we collect"), ("p", "If you use the estimate form, nothing is sent to us by the website. The form writes your request as a text message on your own device, and nothing is sent until you press Send in your messaging app. If you choose to send it, we receive what you put in the message: for example your name, phone number, address or town, the service you want and your project details. We use it only to reply to your request and to do the work you ask about."),
            ("h2", "Cookies and tracking"), ("p", "This site does not set its own cookies and does not run analytics or advertising trackers. Fonts and images are served from this site, not from a third party."),
            ("h2", "Third parties"), ("p", "Links to Google reviews take you to Google, which has its own privacy policy. If you open the Copy or Text options, your device's apps handle the message under their own policies."),
            ("h2", "Sharing"), ("p", "We don't sell your information."),
            ("h2", "Contact"), ("p", "Questions or requests to delete your information: call 610-357-1098.")],
  privacy_draft="Draft for owner review. This describes how the site currently behaves. Have it reviewed before relying on it.",
 ),
 "es": dict(
  home_title="Cuidado de césped, hardscaping y paisajismo en Royersford, PA",
  home_desc="Paisajismo con dueño al frente en Royersford y el condado de Chester, PA: cuidado del césped, diseño de paisajes, hardscaping, muros de contención, drenaje, nivelación y limpieza de temporada. Solicite una cotización gratis.",
  eyebrow="Royersford y el condado de Chester, PA",
  h1="Espacios exteriores bien hechos, y un equipo que responde.",
  lead="Cuidado del césped, diseño de paisajes, hardscaping y muros de contención con el dueño al frente. Comunicación clara, precios justos y una revisión de seguimiento al terminar el trabajo.",
  proof=[("Dirigido por su dueño, Bryan J. Wolf", ""), ("Cotizaciones", "gratis")],
  trust=["Profesional", "Amable", "Confiable", "Precios justos", "Trabajo hermoso"],
  services_h="Lo que hacemos", services_sub="Desde el corte semanal hasta la renovación completa del patio, un solo equipo local se encarga.",
  cards=[("lawn-care", "Cuidado del césped y mantenimiento", "Corte, recorte, mantenimiento del jardín y manejo continuo del paisaje para que su propiedad siempre se vea cuidada.", ["Corte y mantenimiento de césped", "Mantenimiento de jardines", "Manejo del paisaje", "Servicios de jardinería"]),
         ("landscape-design", "Diseño e instalación de paisajes", "Camas, bordes, plantas y mantillo diseñados según cómo usa su jardín.", ["Diseño de paisajes y jardines", "Instalación de paisajes", "Decoración de jardín", "Paisajismo con árboles"]),
         ("hardscaping", "Hardscaping", "Trabajo duradero de piedra y adoquines que agrega espacio útil y mejor aspecto.", ["Pavimentación de entradas y caminos", "Construcción de escalones", "Paisajismo con piedra y roca", "Paisajismo de caminos y entradas"]),
         ("retaining-walls", "Muros de contención", "Corrija pendientes con muros hechos para durar.", ["Muros de contención", "Muros con escalones", "Nivelación de pendientes"]),
         ("drainage-grading", "Drenaje y nivelación", "Aleje el agua de su casa y arregle las zonas encharcadas.", ["Drenaje de jardines", "Nivelación y cambio de pendiente", "Nivelación del terreno"]),
         ("sod-seeding", "Aireación, césped en rollo y siembra", "Empiece un césped nuevo o repare uno cansado con la preparación y los materiales correctos.", ["Instalación de césped en rollo", "Siembra de pasto", "Paisajismo de césped"]),
         ("seasonal-cleanup", "Limpieza de temporada", "Limpiezas de primavera y retiro de hojas en otoño.", ["Recolección y retiro de hojas", "Mantillo y control de maleza"]),
         ("tree-snow", "Árboles y remoción de nieve", "Ayuda cuando el clima se complica.", ["Trabajo con árboles", "Remoción de nieve"])],
  work_h="Vea la diferencia",
  process_h="Cómo funciona",
  steps=[("Solicite una cotización", "Llene el formulario corto o llame. Nos avisan de inmediato."),
         ("Le respondemos", "Por mensaje de texto o llamada, con preguntas o una hora para ver su propiedad."),
         ("Cotización clara y justa", "Usted ve el trabajo y el precio antes de que empecemos."),
         ("Terminado a tiempo y luego una revisión", "Terminamos lo prometido y damos seguimiento para asegurarnos de que esté contento.")],
  reviews_h="Lo que dicen los vecinos",
  area_h="Atendemos Royersford y el condado de Chester",
  area_p="Trabajamos en Royersford y el área cercana. ¿No sabe si lo cubrimos? Envíe una solicitud y le avisamos.",
  why_h="Por qué nos eligen",
  why=["Dueño al frente: trata con las personas que hacen el trabajo", "Respuestas claras y seguimiento rápido", "Precios justos, sin sorpresas", "Lugares de trabajo limpios y ordenados"],
  gallery_title="Galería: ideas de antes y después", gallery_desc="Transformaciones de antes y después: muros de contención, caminos, patios, entradas, camas de jardín y céspedes nuevos en Royersford y el condado de Chester, PA.",
  gallery_h="Galería",
  faq_title="Preguntas frecuentes", faq_desc="Respuestas sobre cotizaciones, área de servicio, horarios y servicios de Wolf's Landscaping Services en Royersford, PA.", faq_h="Preguntas frecuentes",
  faq_foot="¿Todavía tiene una pregunta?", faq_foot_link="Envíenos una solicitud",
  reviews_title="Reseñas de clientes",
  reviews_desc="Lo que dicen los clientes de Wolf's Landscaping Services en Royersford y el condado de Chester, PA, según las reseñas de Google del negocio.",
  rpage_h="Reseñas de clientes",
  reviews_lead="Lo que dicen nuestros clientes en Google.",
  reviews_note="Las reseñas se copiaron de nuestro perfil de Google al 5 de octubre de 2026, en inglés tal como las escribieron los clientes. Los tiempos se muestran como Google los mostró ese día.",
  reviews_partial="Mostrando {n} de {total} reseñas.",
  about_title="Nosotros: paisajismo con el dueño al frente en Royersford, PA",
  about_desc="Wolf's Landscaping Services es una empresa de paisajismo con el dueño al frente en Royersford y el condado de Chester, PA. Conozca cómo trabajamos y qué dicen nuestros clientes.",
  about_h="Sobre Wolf's Landscaping Services",
  about_lead="Un equipo de paisajismo con el dueño al frente, al servicio de Royersford y el condado de Chester, PA.",
  about_who_h="Quiénes somos",
  about_who=["Wolf's Landscaping Services es una empresa de paisajismo con el dueño al frente, que atiende Royersford y el área cercana del condado de Chester. Cuando usted llama o envía una solicitud, trata con las personas que realmente trabajarán en su propiedad.",
             "Cuidamos céspedes y jardines semana a semana, y también hacemos los trabajos más grandes: camas y plantas, caminos y escalones, muros de contención, drenaje y nivelación, céspedes nuevos, limpiezas de temporada, trabajo con árboles y remoción de nieve."],
  about_work_h="Cómo trabajamos",
  about_values=[("Nos comunicamos", "Lo mantenemos informado desde su primera solicitud hasta el trabajo terminado."),
                ("Cumplimos lo que dicen las reseñas", "Los clientes en Google nos describen como profesionales, amables, minuciosos y económicos. Esos son los estándares que buscamos en cada trabajo."),
                ("Precios claros y justos", "Recibe un precio claro antes de empezar cualquier trabajo, sin sorpresas."),
                ("Damos seguimiento", "Después de un trabajo hacemos una revisión para asegurarnos de que esté contento con el resultado.")],
  about_say_h="Lo que dicen los clientes",
  about_quotes=[("Extremely professional company.", "Reseña de Google"),
                ("I would recommend this service to anyone.", "Reseña de Google"),
                ("They went above and beyond.", "Reseña de Google")],
  about_owner_h="Conozca al dueño", about_story_h="Nuestra historia", about_creds_h="Credenciales",
  contact_title="Contacto y cotización gratis", contact_desc="Solicite una cotización gratis de paisajismo a Wolf's Landscaping Services en Royersford y el condado de Chester, PA. Llame o envíe su solicitud por mensaje de texto.", contact_h="Contacto y cotización gratis",
  contact_lead="Cuéntenos sobre su proyecto. Le respondemos por mensaje de texto o llamada.",
  contact_call="¿Prefiere hablar? Llame al", contact_miss="O envíe sus datos con el formulario y le responderemos.",
  join_title="Únase al equipo: empleos de jardinería en Royersford, PA",
  join_desc="Trabaje con Wolf's Landscaping Services en Royersford, PA. Árboles, hardscaping, cuidado del césped y remoción de nieve. Llame o envíe un mensaje para decirnos que le interesa.",
  join_h="Únase a la manada",
  join_lead="Wolf's Landscaping Services es un negocio dirigido por su dueño y siempre nos da gusto saber de personas trabajadoras en el área de Royersford y el condado de Chester.",
  join_poster_alt="Cuatro lobos ilustrados con ropa de trabajo verde, uno con motosierra, uno cargando adoquines, uno con una orilladora y uno con una pala para nieve, bajo las palabras Join the Pack",
  join_intro=["Un buen trabajo requiere un buen equipo. Hacemos céspedes, hardscaping, árboles y nieve, y las personas en nuestros trabajos son lo que hace que todo se vea bien.",
             "Si le enorgullece hacer bien su trabajo y llegar cuando dice que va a llegar, queremos saber de usted. Díganos qué tipo de trabajo le interesa."],
  join_roles_h="Dónde podría encajar",
  join_roles=[("Árboles", "Trabajo con árboles y limpieza.", "tree-snow", "trees", "Lobo ilustrado con sudadera verde sosteniendo una motosierra"),
              ("Hardscape", "Adoquines, caminos, patios y muros de contención.", "hardscaping", "hardscape", "Lobo ilustrado con ropa de trabajo cargando bloques de adoquín junto a un muro de piedra"),
              ("Césped", "Corte, recorte y cuidado continuo del césped.", "lawn-care", "lawn", "Lobo ilustrado con gorra usando una orilladora"),
              ("Nieve", "Remoción de nieve con quitanieves y pala en invierno.", "tree-snow", "snow", "Lobo ilustrado con gorro de lana palando nieve")],
  join_look_h="Lo que buscamos",
  join_look=["Llega a tiempo y listo para trabajar", "Se enorgullece de un trabajo limpio y terminado", "Trabaja con seguridad y cuida al equipo", "Es amable y directo con los clientes"],
  join_apply_h="Cómo aplicar",
  join_apply_p="Llámenos o envíenos un mensaje con su nombre, el tipo de trabajo que le interesa y su experiencia. ¿No tiene experiencia con alguna herramienta o trabajo? Dígalo y pregunte.",
  join_sms="Enviar mensaje", join_call="Llamar",
  join_sms_body="Hola Wolf's Landscaping, me interesa unirme al equipo. Mi nombre es: ",
  join_note="Esta página es sobre trabajar con nuestro equipo. Para una cotización gratis en su propiedad, use la página de contacto.",
  visit_h="Nuestra oficina", visit_p="Nos encuentra en Main Street, en Royersford.", directions="Cómo llegar", view_map="Ver en Google Maps",
  form=dict(name="Nombre", phone="Teléfono", email="Correo electrónico (opcional)", address="Dirección o ciudad de la propiedad", service="Servicio que necesita", choose="Elija uno…",
            message="Cuéntenos sobre el proyecto", pref="Mejor forma de contactarlo", prefs=["Mensaje de texto", "Correo electrónico", "Llamada"],
            submit="Preparar mi solicitud", help="Escribiremos su solicitud como mensaje de texto y usted elige cómo enviarla. ¿Prefiere hablar? Llame al 610-357-1098.",
            ready="Su solicitud está lista.", choose_how="Elija cómo enviarla:", text_btn="Enviar por texto", copy_btn="Copiar mensaje", call_btn="Mejor llamar",
            note="No se envía nada hasta que usted presione Enviar en su aplicación de mensajes.", copied="Copiado. Péguelo en un mensaje o correo, o llame al 610-357-1098.", copyfail="No se pudo copiar automáticamente. Por favor llame al 610-357-1098.",
            hi="Hola Wolf's Landscaping, quiero una cotización gratis. (Cliente que habla español / Spanish-speaking customer)", lbl=dict(name="Nombre (Name)", phone="Teléfono (Phone)", email="Correo (Email)", address="Dirección o ciudad (Address or town)", service="Servicio (Service needed)", pref="Mejor forma de contacto (Best way to reach me)", details="Detalles del proyecto (Project details)"),
            services=["Cuidado del césped y mantenimiento", "Diseño e instalación de paisajes", "Hardscaping (camino, escalones, piedra)", "Muro de contención", "Drenaje / nivelación", "Aireación, césped en rollo o siembra", "Limpieza de temporada / hojas", "Trabajo con árboles", "Remoción de nieve", "Otro"]),
  privacy_title="Política de privacidad", privacy_desc="Cómo Wolf's Landscaping Services maneja la información enviada a través de este sitio web.",
  privacy_h="Política de privacidad",
  privacy=[("h2", "Qué recopilamos"), ("p", "Si usa el formulario de cotización, el sitio web no nos envía nada. El formulario escribe su solicitud como mensaje de texto en su propio dispositivo, y no se envía nada hasta que usted presione Enviar en su aplicación de mensajes. Si decide enviarlo, recibimos lo que usted ponga en el mensaje: por ejemplo su nombre, número de teléfono, dirección o ciudad, el servicio que quiere y los detalles del proyecto. Lo usamos solo para responder a su solicitud y hacer el trabajo que pide."),
            ("h2", "Cookies y rastreo"), ("p", "Este sitio no coloca sus propias cookies ni usa análisis o rastreadores publicitarios. Las fuentes y las imágenes se sirven desde este sitio, no desde un tercero."),
            ("h2", "Terceros"), ("p", "Los enlaces a reseñas de Google lo llevan a Google, que tiene su propia política de privacidad. Si usa las opciones de copiar o enviar por texto, las aplicaciones de su dispositivo manejan el mensaje según sus propias políticas."),
            ("h2", "Compartir"), ("p", "No vendemos su información."),
            ("h2", "Contacto"), ("p", "Preguntas o solicitudes para borrar su información: llame al 610-357-1098.")],
  privacy_draft="Borrador para revisión del dueño. Describe cómo se comporta el sitio actualmente. Haga que lo revisen antes de confiar en él.",
 ),
}
